In [1]:
import numpy as np
x = np.random.randint(low=0, high=100, size=100)

# Compute frequency and bins
frequency, bins = np.histogram(x, bins=10, range=[0, 100])

# Pretty Print
for b, f in zip(bins[1:], frequency):
    print(round(b, 1), ' '.join(np.repeat('*', f)))

10.0 * * * * * * * * * * * * *
20.0 * * * * * * * *
30.0 * * * * * * * * *
40.0 * * * * * * * * * * * * *
50.0 * * * * * * * * *
60.0 * * * * * * * * * * * *
70.0 * * * * * * * *
80.0 * * * * * *
90.0 * * * * * * * *
100.0 * * * * * * * * * * * * * *


In [2]:
x

array([87, 18, 25, 44, 90, 55, 26,  7, 26, 96,  5, 90, 55, 89, 45, 90, 37,
       36,  5, 91, 93, 70, 68, 48, 70,  4, 72, 12, 68, 14, 57, 59, 35, 65,
        9, 42, 30, 12, 46, 91, 16, 39, 56, 92, 93, 45, 34, 23, 80, 91,  5,
       79, 47, 84, 36, 38, 28, 37, 39, 85,  6, 67, 76, 55, 23, 55, 36, 51,
       32, 96, 29,  5, 55, 89, 93, 85,  9, 11, 36, 70, 49, 61, 92, 48, 51,
       69,  0, 60,  4, 68,  9, 84, 22, 21, 51, 97,  9, 52, 19, 18])

In [11]:
frequency

array([ 7, 17,  9,  9,  6, 12,  8,  7, 12, 13], dtype=int64)

In [12]:
bins

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])